# Generated by Django 4.1.7 on 2023-03-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=20, verbose_name='user Name')),
                ('fullName', models.CharField(max_length=50, verbose_name='full Name')),
            ],
        ),
    ]
